apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231102122517.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231102122517.0.0+build.02e9424
  releaseNotes: |
    Release v20231102122517.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-02-11-2023-07-14-38-676731394/where-for-dinner-my-apps-bundle@sha256:f37ec25d5351eea875d796f8622b0211c3cf8ff48f25ba241f1149f8f0255386
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

